---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kinesis
  labels:
    name: kinesis
    app: kinesis
spec:
  serviceName: "kinesis"
  replicas: 1
  selector:
    matchLabels:
      app: kinesis
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4567"
      labels:
        name: kinesis
        app: kinesis
    spec:
      containers:
        - image: saidsef/aws-kinesis-local
          name: kinesis
          ports:
            - protocol: TCP
              containerPort: 4567
              name: kinesis
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests:
              memory: 128Mi
              cpu: 100m
          livenessProbe:
            exec:
              command:
                - pgrep
                - node
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
                port: 4567
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: kinesis-storage
              mountPath: /data
              subPath: data
      volumes:
        - name: kinesis-storage
          emptyDir: {}
